### ISSUE TITLE
Mask loading error 

### ISSUE THREAD

**Issue by 123rc** [darkbiologist/Retinal-Vessel-Segmentation-using-variants-of-UNET#2]
I am using covid segmentation dataset . While loading mask dataset it is adding fifth ,sixth and seventh dimension to the dataset

**Comment by arkanivasarkar** [comment]
The code here expects mask images with a single channel. 
If you are using this dataset (https://www.kaggle.com/competitions/covid-segmentation/data), then please modify the input mask data or code accordingly as this dataset contains masks with 4 channels.

**Comment by 123rc** [comment]
No I am using this dataset (
https://www.kaggle.com/datasets/tawsifurrahman/covid19-radiography-database)

**Comment by arkanivasarkar** [comment]
Then please check if the mask images have a single channel only by loading an image and printing its shape.
